---
title: "TD2026"
author: "Nicolas Saby"
date: "2026-01-07"
output: html_document
---

# La zone du domaine

on tire au hasard dans les strates 4 nouveaux points pour commencer

Pour cela il faut charger les strates en premier lieu

```{r}
library(terra)
strate <- rast("output/strates.tiff")
crs(strate) <- "+init=epsg:2154"
plot(strate)

```

Lire les anciennes positions des unités d'échantillonnage

```{r}
UE2025 <- vect("output/PointsParc.shp")
# UE2025 <- read_sf("output/PointsParc.shp")

library(tmap)

tm_shape(strate) + tm_raster("clusters") +
  tm_shape(UE2025) + tm_dots()

```

Tirer au hasard 4 points par strates

- avec st_sample

```{r}

UE2026 <- spatSample(strate[[4]] ,
           size = 10,
           as.points=TRUE,
           method= "stratified")


tm_shape(strate) + 
  tm_raster("clusters" ,
          col.scale = tm_scale_categorical(values = terrain.colors(4)) 
          ) + 
  tm_shape(UE2025) + 
  tm_dots() +
  tm_shape(UE2026) +
  tm_symbols(fill = "clusters",size = .3,
          fill.scale = tm_scale_categorical(n=4)
)

```
Exportation du shape file

```{r}

terra::writeVector(UE2026)

```

